# Generated by Django 3.1 on 2020-08-13 04:21

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email_p', models.EmailField(max_length=100, unique=True)),
                ('email_j', models.EmailField(max_length=100, unique=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('direction', models.CharField(max_length=200)),
                ('url_linked', models.URLField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical', models.CharField(max_length=50)),
                ('professional', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('profile_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileProject', to='profile.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='profileSkill', to='profile.Skill'),
        ),
        migrations.CreateModel(
            name='PersonalReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_personal_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profilePersonalReference', to='profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('diploma', models.CharField(max_length=200)),
                ('profile_Education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileEducation', to='profile.profile')),
            ],
        ),
    ]
