# Generated by Django 3.1 on 2020-09-02 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20200826_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name_place',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('name_place', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('profile_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileWork', to='profile.profile')),
            ],
        ),
    ]
