# Generated by Django 3.1 on 2020-09-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20200902_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_project',
            field=models.URLField(default=''),
        ),
    ]
